version: "3.8"

services:
  react_app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - frontend-network

networks:
  frontend-network:
